### ISSUE TITLE
Complete the frontend

### ISSUE THREAD

**Issue by Bharath1910** [learn-hands-on/Quote-Guesser-Web#1]
I need you to create a separate branch and start working on the website. Creating a separate branch is important because I have locked the main branch, and you cannot directly commit on the main branch. I need the HTML to be named as ``index.html`` and if you have any images, keep it inside ``images`` folder and name the CSS file as ``styles.css``

You need to recreate the below web page

![Image](https://user-images.githubusercontent.com/72338995/212960188-e93b2c87-ba59-434b-b79f-55d240f9e60f.png)

for better clarity, you can view [here](https://dribbble.com/shots/13680935-Daily-UI-Challenge-092-FAQ)

**Comment by roni-2004** [comment]
Noted, I'll wrap this up by this week.

**Comment by Bharath1910** [comment]
Well done @roni-2004
