### ISSUE TITLE
Complete the backend

### ISSUE THREAD

**Issue by Bharath1910** [learn-hands-on/quote-guesser-web#2]
Create the backend using vanilla JavaScript

- [x] Fetch one quote using quotable API [Link](https://api.quotable.io/random)
- [x] Update the frontend to show the fetched quote
- [x] Take the input and validate if the author of the quote matches with the user input
- [x] If they match, show a green tick
- [x] Else, show a red tick

**Comment by shaunakc11** [comment]
PUT UR FUCKING HANDS UP 🔫
